// 集成测试 runner — 自动发现 scripts/integration/*.js 并串行跑
//   每个脚本约定：成功 → console 输出含 "==== N/N PASS ===="；失败 → exit 1 + 输出 FAILURES
//   runner 用 child_process.spawnSync 隔离进程跑（避免脚本互相污染 module cache / global state）
//
// 用法：node scripts/integration-runner.js
//      npm run test:integration
//
// 新加集成测试：直接在 scripts/integration/ 下新建 .js 文件即可，runner 自动抓
//   命名规范：<module>-<feature>.js，按业务模块（避免版本前缀）
//   详见 rules/integration-test-policy.md
//
// v2.1.9 SR-policy-1（spec §12.2 / T32a）：runner 末尾把当前清单 in-place 写回 rules/integration-test-policy.md §七
//   - 全 PASS 才更新（任一 FAIL → 跳过同步以免污染清单）
//   - 时间戳行 + DO NOT EDIT 注释
//   - 同时把 markdown 表打到 stdout（CI / 本地都能看到）

const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const INTEGRATION_DIR = path.join(__dirname, 'integration');
const POLICY_PATH = path.join(__dirname, '..', 'rules', 'integration-test-policy.md');

function findIntegrationScripts() {
  if (!fs.existsSync(INTEGRATION_DIR)) {
    console.error(`[integration-runner] 目录不存在：${INTEGRATION_DIR}`);
    process.exit(1);
  }
  return fs.readdirSync(INTEGRATION_DIR)
    .filter((f) => f.endsWith('.js'))
    .sort()
    .map((f) => path.join(INTEGRATION_DIR, f));
}

function runScript(scriptPath) {
  const name = path.basename(scriptPath, '.js');
  process.stdout.write(`\n[integration] ▶ ${name} ... `);
  const start = Date.now();
  const result = spawnSync('node', [scriptPath], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe']
  });
  const elapsedMs = Date.now() - start;
  const stdout = result.stdout || '';
  const stderr = result.stderr || '';
  const combined = stdout + stderr;

  // 尝试从输出抽 "N/N PASS" 数字
  const passMatch = combined.match(/(\d+)\/(\d+) PASS/);
  const summary = passMatch ? `${passMatch[1]}/${passMatch[2]}` : '(no count)';
  // v2.1.9 SR-policy-1：拆出 用例数（pass count）/ 总数（total）用于清单生成
  const passedCount = passMatch ? Number(passMatch[1]) : null;
  const totalCount = passMatch ? Number(passMatch[2]) : null;

  if (result.status === 0) {
    process.stdout.write(`PASS ${summary} (${elapsedMs}ms)\n`);
    return { name, ok: true, summary, elapsedMs, passedCount, totalCount };
  }

  process.stdout.write(`FAIL (${elapsedMs}ms)\n`);
  // SR4 强化：长 stderr / stdout 截最后 30 行（保留最相关的错误信息，避免日志被淹没）
  const MAX_TAIL_LINES = 30;
  const tailLines = (text) => {
    const lines = text.split('\n');
    if (lines.length <= MAX_TAIL_LINES) return text;
    return `... (省略前 ${lines.length - MAX_TAIL_LINES} 行)\n` + lines.slice(-MAX_TAIL_LINES).join('\n');
  };
  console.error('  --- stdout (tail) ---');
  console.error(tailLines(stdout).split('\n').map((l) => '  ' + l).join('\n'));
  if (stderr) {
    console.error('  --- stderr (tail) ---');
    console.error(tailLines(stderr).split('\n').map((l) => '  ' + l).join('\n'));
  }
  return { name, ok: false, summary, elapsedMs, exitCode: result.status, passedCount, totalCount };
}

// v2.1.9 SR-policy-1：把 results 组装为 markdown 表（含时间戳 + DO NOT EDIT 注释）
//   format：spec §12.2.1
//   ts：ISO 8601 with +08:00 偏移（中国时区固定显示，便于审计跨时区一致）
function buildPolicyChecklistSection(results, { timestamp = formatChinaTimestamp() } = {}) {
  const lines = [];
  lines.push('## 七、当前集成测试清单（自动同步）');
  lines.push('');
  lines.push(`<!-- auto-generated by scripts/integration-runner.js, last-updated: ${timestamp} -->`);
  lines.push('<!-- DO NOT EDIT MANUALLY — modify scripts/integration/*.js then re-run `npm run test:integration` -->');
  lines.push('');
  lines.push('| 脚本 | 用例数 | 断言数 | 耗时 (ms) |');
  lines.push('|---|---|---|---|');

  let totalCases = 0;
  let totalAsserts = 0;
  let totalMs = 0;
  for (const r of results) {
    const cases = r.passedCount == null ? '-' : r.passedCount;
    // 子断言数无法独立解析（脚本内 assertEq/assertTrue 每次 +1 进 passed，与"用例数"同源）
    //   → 双列同值即可符合 spec §12.2.1 表头要求 + 不丢信息
    const asserts = r.totalCount == null ? '-' : r.totalCount;
    lines.push(`| \`${r.name}.js\` | ${cases} | ${asserts} | ${r.elapsedMs} |`);
    if (typeof r.passedCount === 'number') totalCases += r.passedCount;
    if (typeof r.totalCount === 'number') totalAsserts += r.totalCount;
    totalMs += r.elapsedMs;
  }
  lines.push(`| **合计** | **${totalCases}** | **${totalAsserts}** | **${totalMs}** |`);
  lines.push('');
  lines.push('> 同步策略：runner 末尾全 PASS 时 in-place 替换本章节；任一脚本 FAIL → 本章节不更新（避免被损坏数据覆盖）。');
  lines.push('');
  return lines.join('\n');
}

// v2.1.9 SR-policy-1：ISO 时间戳 + 中国时区固定 +08:00（避免在不同 OS / 不同时区机器跑产生混乱差异）
function formatChinaTimestamp(date = new Date()) {
  // 转换为东八区（UTC + 8h）
  const cnMs = date.getTime() + 8 * 60 * 60 * 1000;
  const d = new Date(cnMs);
  const pad = (n) => String(n).padStart(2, '0');
  const y = d.getUTCFullYear();
  const mo = pad(d.getUTCMonth() + 1);
  const da = pad(d.getUTCDate());
  const h = pad(d.getUTCHours());
  const mi = pad(d.getUTCMinutes());
  const se = pad(d.getUTCSeconds());
  return `${y}-${mo}-${da}T${h}:${mi}:${se}+08:00`;
}

// v2.1.9 SR-policy-1：in-place 替换 rules/integration-test-policy.md 的 §七 章节
//   定位：从 `## 七、` 开头 → 下一个 `## ` 之前（或文件末）
//   失败容忍：替换失败仅 console.warn，不阻塞 runner exit code
function syncPolicyChecklist(results, { policyPath = POLICY_PATH, now = new Date() } = {}) {
  if (!fs.existsSync(policyPath)) {
    console.warn(`[SR-policy-1] policy 文件不存在，跳过同步：${policyPath}`);
    return { synced: false, reason: 'policy-not-exist' };
  }

  let original;
  try {
    original = fs.readFileSync(policyPath, 'utf8');
  } catch (err) {
    console.warn(`[SR-policy-1] 读取 policy 失败，跳过同步：${err && err.message}`);
    return { synced: false, reason: 'read-failed', error: err && err.message };
  }

  const newSection = buildPolicyChecklistSection(results, { timestamp: formatChinaTimestamp(now) });

  // 定位 §七 章节：从 `## 七、` 开始到下一个 `## ` 章节标题（不含）或文件末
  //   注意：必须用非贪婪 + lookahead 到 `\n## `（避免误吃掉后续章节）
  const sectionRegex = /## 七、[\s\S]*?(?=\n## |$(?![\s\S]))/;
  let updated;
  if (sectionRegex.test(original)) {
    updated = original.replace(sectionRegex, newSection);
  } else {
    // 既有文件无 §七 → 不创造新章节（避免误位置）；仅警告
    console.warn(`[SR-policy-1] policy 文件无 §七 章节，跳过同步`);
    return { synced: false, reason: 'no-section-seven' };
  }

  if (updated === original) {
    // 内容完全一致 → 无写入需要（节省 git diff 噪音）
    return { synced: false, reason: 'no-change', section: newSection };
  }

  try {
    fs.writeFileSync(policyPath, updated, 'utf8');
    console.log(`\n[SR-policy-1] rules/integration-test-policy.md §七 已自动同步`);
  } catch (err) {
    console.warn(`[SR-policy-1] 写入 policy 失败，跳过同步：${err && err.message}`);
    return { synced: false, reason: 'write-failed', error: err && err.message };
  }

  return { synced: true, section: newSection };
}

function main() {
  const scripts = findIntegrationScripts();
  if (scripts.length === 0) {
    console.warn('[integration-runner] 未找到任何 scripts/integration/*.js');
    return;
  }

  console.log(`==== integration runner: ${scripts.length} 个脚本 ====`);
  const results = scripts.map(runScript);
  const failures = results.filter((r) => !r.ok);
  const totalElapsed = results.reduce((s, r) => s + r.elapsedMs, 0);

  console.log(`\n==== 汇总（${totalElapsed}ms 总耗时）====`);
  results.forEach((r) => {
    const mark = r.ok ? '✓' : '✗';
    console.log(`  ${mark} ${r.name} ${r.summary} (${r.elapsedMs}ms)`);
  });

  if (failures.length > 0) {
    console.error(`\n${failures.length} 个集成脚本失败，integration test FAIL`);
    // FAIL 不同步 — 避免不完整数据覆盖既有清单
    process.exit(1);
  }

  // v2.1.9 SR-policy-1：全 PASS → in-place 同步清单 + stdout 打印
  const syncResult = syncPolicyChecklist(results);
  console.log('\n=== 当前清单 ===\n' + (syncResult.section || buildPolicyChecklistSection(results)));

  console.log(`\n全部 ${results.length} 个集成脚本通过 ✓`);
}

if (require.main === module) {
  main();
}

// v2.1.9 SR-policy-1：导出可测试函数（unit test 用）
module.exports = {
  buildPolicyChecklistSection,
  syncPolicyChecklist,
  formatChinaTimestamp,
};
