'use strict';

const POSITION_IMPORT_PROTOCOL_VERSION = 1;
const POSITION_IMPORT_LEDGER_SCHEMA_VERSION = 1;
const POSITION_SST_MEMORY_BUDGET_BYTES = 64 * 1024 * 1024;
const POSITION_SST_LRU_MAX_ENTRIES = 8192;
const POSITION_IMPORT_MAX_ERROR_DETAILS = 100;

const POSITION_IMPORT_ENGINES = Object.freeze({
  STREAMING: 'streaming',
  LEGACY_WORKER: 'legacy-worker',
  DISABLED: 'disabled'
});

const POSITION_IMPORT_COMMANDS = Object.freeze({
  BANK_PREPARE: 'BANK_PREPARE',
  BANK_APPLY: 'BANK_APPLY',
  SOURCE_PREPARE_AND_APPLY: 'SOURCE_PREPARE_AND_APPLY',
  ACCOUNT_APPLY: 'ACCOUNT_APPLY',
  DELETE_BANK: 'DELETE_BANK',
  DELETE_SOURCE: 'DELETE_SOURCE',
  REBUILD_FUND_TRANSFER_MAPPING: 'REBUILD_FUND_TRANSFER_MAPPING',
  ENSURE_LARGE_IMPORT_INDEXES: 'ENSURE_LARGE_IMPORT_INDEXES'
});

const POSITION_IMPORT_MESSAGE_TYPES = Object.freeze({
  START_JOB: 'START_JOB',
  PROGRESS: 'PROGRESS',
  PREFLIGHT_READY: 'PREFLIGHT_READY',
  APPLY_GRANTED: 'APPLY_GRANTED',
  FILE_COMMITTED: 'FILE_COMMITTED',
  COMPLETE: 'COMPLETE',
  FATAL: 'FATAL',
  CANCEL: 'CANCEL',
  CANCEL_ACK: 'CANCEL_ACK'
});

function normalizePositionImportEngine(value = process.env.POSITION_IMPORT_ENGINE) {
  const normalized = String(value || '').trim().toLowerCase();
  return Object.values(POSITION_IMPORT_ENGINES).includes(normalized)
    ? normalized
    : POSITION_IMPORT_ENGINES.DISABLED;
}

module.exports = {
  POSITION_IMPORT_PROTOCOL_VERSION,
  POSITION_IMPORT_LEDGER_SCHEMA_VERSION,
  POSITION_SST_MEMORY_BUDGET_BYTES,
  POSITION_SST_LRU_MAX_ENTRIES,
  POSITION_IMPORT_MAX_ERROR_DETAILS,
  POSITION_IMPORT_ENGINES,
  POSITION_IMPORT_COMMANDS,
  POSITION_IMPORT_MESSAGE_TYPES,
  normalizePositionImportEngine
};
